name: amwater persistent
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7.7' # install the python version needed

    - name: set env variables
      env:
          ADDR: ${{SECRETS.ADDR}}
          SLACK_HOOK : ${{SECRETS.SLACK_HOOK}}
    - name: install packages
        run:|
          python -m pip install --upgrade pip
          pip install -U pip setuptools
          pip install amwater
    - name: script check
      uses: jannekem/run-python-script-action@v1
      with:
        script: |
          import subprocess
          addr = os.environment['ADDR']
          slack_hook = os.environment['SLACK_HOOK']
          subprocess.call(f'amwater check --address {addr} --webhook {slack_hook}')
